[Dixit API] create dixit / story / playcard / guess
Game-as-a-Service/dixit-as-a-service pull request #8
Opened 2021-08-19 07:28 UTC by Wally5077

[POST] /api/dixit
[PUT] /api/dixit/{dixitId}/rounds/{round}/story
[PUT] /api/dixit/{dixitId}/rounds/{round}/playcard
[PUT] /api/dixit/{dixitId}/rounds/{round}/guess

2021-08-19 07:32 UTC, Johnny850807 requested changes
Reviewed your API design

2021-08-19 07:32 UTC, Johnny850807 commented on spring-boot-dixit/src/main/java/tw/wally/dixit/controllers/DixitController.java
> +    @PutMapping("/{dixitId}/rounds/{round}/guess")
Not RESTFul (who guesses?)

2021-08-19 07:32 UTC, Johnny850807 commented on spring-boot-dixit/src/main/java/tw/wally/dixit/controllers/DixitController.java
> +    @PutMapping("/{dixitId}/rounds/{round}/playcard")
Not RESTFul (who plays?)

2021-08-19 09:01 UTC, Johnny850807 requested changes
Review for a while

2021-08-19 09:01 UTC, Johnny850807 commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +                .findFirst().orElseThrow();
Don't leak the internal structure of Dixit.

Consider adding a new method `getGuessedCard(player:Player): Optional<Card>` in Dixit

2021-08-19 09:01 UTC, Johnny850807 commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +        assertEqualsIgnoreOrder(expectedGamers, actualGamers);
Ditto

2021-08-21 12:33 UTC, Johnny850807 requested changes
Rename all of the gamers to players

They are all the players and only players.

2021-08-21 12:33 UTC, Johnny850807 commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    private void assertEachGamerPlayCard(Collection<Player> expectedGamers) {
They are not gamers.

UL

2021-08-21 12:33 UTC, Johnny850807 commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +        assertEqualsIgnoreOrder(expectedGamers, actualGamers);
They are not gamers.

UL

2021-08-21 12:42 UTC, Johnny850807 requested changes
Review usecases

2021-08-21 12:42 UTC, Johnny850807 commented on dixit/src/main/java/tw/wally/dixit/usecases/CreateDixitUseCase.java
> +        mayPublishEvents(dixit);
Extract  a `getPlayers` method. Don't mix the DTO conversion code with the use case flow.

```java
        var cards = cardRepository.findAll();
        var dixit = new Dixit(game.id, game.gameSetting.toVictoryCondition(), cards);
        getPlayers(request).forEach(dixit::join);
        dixit.start();
        dixit = dixitRepository.save(dixit);
        mayPublishEvents(dixit);
```

2021-08-21 12:42 UTC, Johnny850807 commented on dixit/src/main/java/tw/wally/dixit/usecases/GuessStoryUseCase.java
> +        var dixit = findDixit(request.gameId);
Don't `var`

No benefits on this.

2021-08-21 12:42 UTC, Johnny850807 commented on dixit/src/main/java/tw/wally/dixit/usecases/GuessStoryUseCase.java
> +                .orElseThrow(() -> new InvalidGameOperationException(format("Player: %s is not guesser", playerId)));
`Player guesser = dixit.getGuesser(playerId);`

2021-08-21 12:42 UTC, Johnny850807 commented on dixit/src/main/java/tw/wally/dixit/usecases/GuessStoryUseCase.java
> +        var playCard = dixit.getPlayCardByCardId(request.cardId);
`PlayCard playCard =  dixit.getPlayCard(request.cardId);`

2021-08-21 12:42 UTC, Johnny850807 commented on dixit/src/main/java/tw/wally/dixit/usecases/PlayCardUseCase.java
> +    }
ditto

2021-08-21 12:42 UTC, Johnny850807 commented on dixit/src/main/java/tw/wally/dixit/usecases/TellStoryUseCase.java
> +    }
ditto

2021-08-24 16:52 UTC, zseqw123 approved these changes
LGTM

2021-08-25 07:43 UTC, Johnny850807 commented on dixit/src/main/java/tw/wally/dixit/usecases/CreateDixitUseCase.java
> +        mayPublishEvents(dixit);
@Wally5077 any update?

2021-08-25 08:13 UTC, Johnny850807 requested changes
Review done

2021-08-25 08:13 UTC, Johnny850807 commented on dixit/src/main/java/tw/wally/dixit/usecases/CreateDixitUseCase.java
> +        dixit.join(game.host.toPlayer());
should be returned from `players`

2021-08-26 10:09 UTC, Chaoyuuu requested changes
This PR is as huge as WATERBALL!

2021-08-26 10:09 UTC, Chaoyuuu commented on dixit/src/test/java/tw/wally/dixit/model/DixitTest.java
> +
Why did you test these again? It is the same as `GameTest`.

2021-08-26 10:15 UTC, wallychen0705 commented on dixit/src/test/java/tw/wally/dixit/model/DixitTest.java
> +
GameTest should be deleted.

2021-08-30 13:21 UTC, Chaoyuuu requested changes
Review Done!

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +
Why did you use `gamers` instead of `players`? What is the difference?

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    }
rename to `...ThenShouldRespondBadRequest`.

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    }
`assertStorytellerTellStory(storyteller);` doesn't imply the statement `CurrentRoundShouldHaveStory` to me. 🤔

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +        assertNull(dixit.getCurrentRound().getStory());
`...ThenShouldRespondBadRequest`.

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +        assertEquals(1, dixit.getNumberOfRounds());
`GivenDixitStartedInFirstRound_WhenStorytellerTellsStoryInSecondRound_ThenShouldRespondBadRequest`

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +        assertEquals(1, dixit.getNumberOfRounds());
rename to `GivenStoryToldInFirstRound_WhenOneGuesserPlaysCardInSecondRound_ThenShouldRespondBadRequest`.

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    }
`GivenEachGuesserPlayedCard..` -> `GiveAllGuessersPlayedCard..`
`givenEachGuesserPlayedCardAndGetDixit();` -> `givenAllGuessersPlayedCardAndGetDixit();`

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    }
Ditto.

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    }
rename to `GivenAllGuessersPlayedCardInFirstRound_WhenOneGuesserGuessStoryInSecondRound_ThenShouldRespondBadRequest`

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    }
Is it better to extract `1` to a constant `FIRST_ROUND` and `2` to `SECOUND_RONUD`? 
This is just a suggestion.

2021-08-30 13:21 UTC, Chaoyuuu commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    }
1. `numberOfRounds` can rename to `currentRound`.
2. `assertEachGuesserPlayCard(guessers);` doesn't imply `ThenCurrentRoundShouldHaveTwoPlayCards`. 
You should rename `assertEachGuesserPlayCard(guessers)` to match the _then_ statement.

2021-09-02 09:56 UTC, Wally5077 commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +
It was called 'gamer' by lobby service, but finally 'gamer' will become 'player' after discussing.

2021-09-02 10:04 UTC, Wally5077 commented on spring-boot-dixit/src/test/java/tw/wally/dixit/DixitControllerTest.java
> +    }
I have changed the method name to new one which is 'assertCurrentRoundHasStoryWhichToldByStoryteller'

2021-09-04 10:38 UTC, merged